version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    #networks:
    #  - localnet

  listener:
    image: git.dapp-devs.com:5050/xswap/backend:dev
    pull_policy: always
    command: "python scripts/event_listener.py"
    #networks:
    #  - localnet


  api:
    image: git.dapp-devs.com:5050/xswap/backend:dev
    pull_policy: always
    command: "python scripts/app.py"
    ports:
      - "5001:5001"
    #networks:
    #  - localnet

#networks:
#  localnet:
#    name: localnet
#    driver: bridge
